[package]
name = "live_lib"
version = "0.1.1"
authors = ["dahai-f <1119369173@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.0"
notify = "4.0.15"
error-chain = "0.12.4"
